[project]
name = "ai-real-estate-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.2.5",
    "fastapi>=0.121.1",
    "fastapi-clerk-auth>=0.0.9",
    "langchain[google-genai]>=1.0.5",
    "langchain-openai>=1.0.2",
    "langchain-tavily>=0.2.13",
    "langgraph>=1.0.3",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "tavily-python>=0.7.12",
    "uvicorn>=0.38.0",
]
